[WIP] skeleton evals API & eleuther evals provider
meta-llama/llama-stack pull request #187
Opened 2024-10-04 21:00 UTC by yanxi0830

# Changes
✅ skeleton evals API using inference
✅ integrate with [Eleuther Eval Harness](https://github.com/EleutherAI/lm-evaluation-harness/tree/main) using dummy LM. We need `loglikelihood` return from inference API. 
✅ CustomDataset / HFDataset

-- Not in this PR
🚧  jobs API for background eval scheduling
🚧  batch inference

# Test
- Client
```
python -m llama_stack.apis.evals.client
```

- With Eleuther Eval Harness
![image](https://github.com/user-attachments/assets/a0593175-06a2-418a-945e-3414cd996db9)

![image](https://github.com/user-attachments/assets/2d1282ad-823d-40a7-a908-e5fc48b2aecd)

- With Custom Task
![image](https://github.com/user-attachments/assets/eba2951b-493c-4355-af16-1f3f837afe4c)

2024-10-04 23:03 UTC, raghotham requested changes

2024-10-04 23:03 UTC, raghotham commented on llama_stack/providers/adapters/evals/eleuther/__init__.py
> +# Copyright (c) Meta Platforms, Inc. and affiliates.
should move this over to impls - we use adapters only for remote. I think we should just rename adapters to "remote" move impls to "inline".

2024-10-09 20:49 UTC, yanxi0830 commented on llama_stack/distribution/registry/datasets/dataset_registry.py
> +class DatasetRegistry:
Might need to move these to follow the new registry

2024-10-10 18:36 UTC, yanxi0830 commented
moving to https://github.com/meta-llama/llama-stack/pull/235

2024-10-10 18:36 UTC, closed without merging