WIP: Add generic OpenAI compatible inference provider
meta-llama/llama-stack pull request #195
Opened 2024-10-06 03:39 UTC by terrytangyuan

This PR is refactored from https://github.com/meta-llama/llama-stack/pull/178 to a more generic OpenAI compatible inference provider. Other remote providers that are compatible to OpenAI protocols should be able to use this as a parent class and extend/customize. 

Test output:

```
User>hello world, write me a 2 sentence poem about the moon
Assistant> In the quiet night, the moon whispers,
Silver dreams in the vast cosmic ocean.
```

2024-10-06 15:39 UTC, russellb commented
Thanks for adapting this to be a generic provider! Maybe you could rebase on main since #83 merged? You could make the databricks provider the first example of extending from this.

… assuming there is some customization anyway. If there really isn’t customization, I’d vote for only having the generic one unless customization is necessary. 

Cc @ashwinb

2024-10-06 19:29 UTC, terrytangyuan commented
> Thanks for adapting this to be a generic provider! Maybe you could rebase on main since https://github.com/meta-llama/llama-stack/pull/83 merged? You could make the databricks provider the first example of extending from this.

Just rebased. I think it's better for Databricks provider contributors to adapt this generic provider since I have no way to test any changes on Databricks provider. @ashwinb It would be great if we could merge this as is so we can start leveraging it. 

> assuming there is some customization anyway. If there really isn’t customization, I’d vote for only having the generic one unless customization is necessary.

I agree. We should have the generic one. For others that extends this, we should assess whether it's necessary based on how much customization is needed.

2024-10-06 19:59 UTC, russellb commented
> > assuming there is some customization anyway. If there really isn’t customization, I’d vote for only having the generic one unless customization is necessary.
> 
> I agree. We should have the generic one. For others that extends this, we should assess whether it's necessary based on how much customization is needed.

seems @ashwinb would like to keep it only as shared code and not as a generic provider for now (based on comments in #193).

I guess this PR could adapt to become a refactoring of the databricks provider?

@ashwinb how about the original use case from @terrytangyuan, which was to connect to a remote instance of vllm? Have one called `vllm-remote`?  or have something called `vllm` in both the local and remote parts of the tree, so in the config you'd have `vllm` (implying inline / local) or `remote::vllm` ?

2024-10-10 18:13 UTC, ashwinb requested changes
I don't think llama stack should have a generic OpenAI provider -- at least as yet. We have refactored the existing code to introduce a utility https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/utils/inference/openai_compat.py which is used by all the openai-like providers right now. 

We should see how far this goes. Each provider has slightly different ways of accomplishing things; the API key configuration also can be different. 

The most important issue is that we cannot keep a quality bar on the quality of the llama model output if there's a generic URL behind which a provider can hide.

2024-10-24 23:03 UTC, ashwinb commented
Closing this because we decided to take a different approach using utility functions (in `openai_compat.py`)

2024-10-24 23:03 UTC, closed without merging