add nvidia distribution
meta-llama/llama-stack pull request #565
Opened 2024-12-04 03:29 UTC by cdgamarose-nv

# What does this PR do?

adds nvidia template for creating a distribution using inference adapter for NVIDIA NIMs.

## Test Plan

Please describe:
 Build llama stack distribution for nvidia using the template, docker and conda.
```bash
llama stack build --template nvidia
```
or 
```bash
cd distributions/inline-nvidia/ && docker compose up
```

## Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Ran pre-commit to handle lint / formatting issues.
- [x] Read the [contributor guideline](https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md),
      Pull Request section?
- [x] Updated relevant documentation.
- [ ] Wrote necessary unit or integration tests.

2024-12-04 03:30 UTC, cdgamarose-nv commented
@mattf for viz

2025-01-10 22:04 UTC, cdgamarose-nv commented
I used a dev docker image to test this (distribution-nvidia:dev). Do we push the image to dockerhub, or there a process to follow?

2025-01-14 04:23 UTC, ashwinb commented
@cdgamarose-nv yeah we are setting up CI for automatically uploading dockers when we make them for the supported distributions. Pretty imminent!

2025-01-14 04:25 UTC, ashwinb commented on distributions/inline-nvidia/run.yaml
> +version: '2'
I don't think you need an `inline-nvidia` distro at all?

2025-01-14 19:12 UTC, ashwinb requested changes
need to remove `inline-nvidia`

2025-01-15 22:03 UTC, yanxi0830 commented
> I used a dev docker image to test this (distribution-nvidia:dev). Do we push the image to dockerhub, or there a process to follow?

@cdgamarose-nv yes! we have just added a Github workflow to build docker images and update to dockerhub: https://github.com/meta-llama/llama-stack/actions/workflows/publish-to-docker.yml

2025-01-15 22:03 UTC, yanxi0830 commented
Merging this PR in and rebasing on top to remove `inline-nvidia` template.

2025-01-15 22:03 UTC, yanxi0830 approved these changes

2025-01-15 22:04 UTC, merged

2025-01-15 22:17 UTC, yanxi0830 commented
Removed inline-nvidia template in https://github.com/meta-llama/llama-stack/commit/27e07b44b557c8a37ff24c865b407faa33b67d76