Renames otel config from jaeger to otel
meta-llama/llama-stack pull request #569
Opened 2024-12-05 05:31 UTC by codefromthecrypt

# What does this PR do?

#525 introduced a telemetry configuration named jaeger, but what it really is pointing to is an OTLP HTTP endpoint which is supported by most servers in the ecosystem, including raw opentelemetry collectors, several APMs, and even https://github.com/ymtdzzz/otel-tui

I chose to rename this to "otel" as it will bring in more people to the ecosystem vs feeling it only works with jaeger.  Later, we can use the [standard ENV](https://opentelemetry.io/docs/specs/otel/protocol/exporter/) to configure this if we like so that you can override things with variables people might expect.

Note: I also added to the README that you have to install conda. Depending on experience level of the user, and especially with miniforge vs other ways, I felt this helps.

## Test Plan

I would like to test this, but actually got a little lost. The previous PRs referenced yaml which doesn't seem published anywhere. It would be nice to have a pre-canned setup that uses ollama and turns on otel, but would also appreciate a hand on instructions meanwhile.

## Sources

https://github.com/meta-llama/llama-stack/pull/525

## Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Ran pre-commit to handle lint / formatting issues.
- [x] Read the [contributor guideline](https://github.com/meta-llama/llama-stack/blob/main/CONTRIBUTING.md),
      Pull Request section?
- [ ] Updated relevant documentation.
- [ ] Wrote necessary unit or integration tests.

2024-12-05 17:37 UTC, dineshyv approved these changes

2024-12-05 17:37 UTC, dineshyv commented on llama_stack/providers/inline/telemetry/meta_reference/config.py
There is a description which also mentions jaeger, can that be chagned?

2024-12-05 18:13 UTC, dineshyv commented on llama_stack/providers/remote/telemetry/opentelemetry/opentelemetry.py
> +        if TelemetrySink.OTEL in self.config.sinks:
This file has actually been moved to https://github.com/meta-llama/llama-stack/blob/main/llama_stack/providers/inline/telemetry/meta_reference/telemetry.py. Can this change be made there?

2024-12-06 00:04 UTC, dineshyv requested changes
can you make the requested changes?

2024-12-06 04:34 UTC, codefromthecrypt commented
sure I will rebase and sort it out. thanks!

2024-12-06 18:16 UTC, dineshyv approved these changes

2024-12-06 18:16 UTC, merged